#!/bin/bash 

function print_help {
  echo "usage: "
  echo 'exportdotenv <options>' 
  echo "options:"
  echo "  --print-cmds: print the commands to the console instead of evaluating the immediately"
}

while [ $# -gt 0 ]; do
    case "$1" in
	--help)
            print_help;
            exit 0
            ;;
        --print-cmds)
            PRINT_CMDS=true
            shift 
            ;;
    esac
done


for line in `cat .env`; do
  if [ $PRINT_CMDS ]; then
    echo "export $line";
  else
    export $line;
  fi
done

