#!/bin/bash
#-----------------------------------------------------------------
# 
# Get ipinfo.io
#
# RICK PFAHL <pfahlr@gmail.com>
# 16 MAY 2024
#
# OPTIONS:
# 
#----------------------------------------------------------------


if [ $1 == "-e" ];
  then
    curl https://ipinfo.io/widget/demo/$2
  else curl https://ipinfo.io/$1?token=$IPINFOTOKEN
fi
