#!/bin/bash
pacman_update_executable="yay"
pacman_main_executable="pacman"
pager_of_choice="most"

runcmd () {
  echo "running command: $1"
  eval $1
}

returntomain () {
  read -erp "Return to Main Menu [Y/n]:" continueinp
  if [[ $continueinp != 'n' ]]; then
    mainmenu
    else 
      exit
  fi
}

uninstallorphans () {
  cmd="$pacman_main_executable -Qdtq | sudo $pacman_main_executable -Rns -"
  runcmd "$cmd"
  returntomain
}

deletecahe () {
  echo "deleting cache directory with size:"
  du -sh "$HOME/.cache"
  cmd="rm -rf $HOME/.cache"
  runcmd "$cmd"
  returntomain  
}

pacmanclean () {
  cmd="sudo $pacman_main_executable -Scc"
  runcmd "$cmd"
  returntomain
}

homdiruseage () {
  echo ""
  echo "getting home directory usage summary"
  timestamp="$(date +%s)"
  tempfilename="homedirusage__$timestamp"
  sudo du -sh $HOME/* | grep '[M,G]' > "/tmp/$tempfilename" 
  sudo du -sh $HOME/.* | grep '[M,G]' >> "/tmp/$tempfilename"
  $pager_of_choice /tmp/$tempfilename
  rm /tmp/$tempfilename
  returntomain
} 

listinstalledsizes () {
  ( echo "Package  Size" && expac "%n\t%m" -l'\n' -H M -Q $($pacman_main_executable -Qq)  | sort -rhk 2 ) | column -t | $pager_of_choice
  returntomain
}

systemupdate () {
  cmd="$pacman_update_executable -Syyu --answerdiff N --answerclean N --answeredit N --answerupgrade Y --sudoloop --needed --removemake --noconfirm"
  echo $cmd 
  $cmd
  returntomain
}

mainmenu () {
  menu="
████████████████████████████████████████████████████████████████████████████████
█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
█▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓█
█▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓█
█▓░                                                                          ░▓█
█▓░ (1) Uninstall Orphaned Packages    (2) Run pacman/yay clean              ░▓█
█▓░ (3) Delete Cache                   (4) Summarize Home Directory Usage    ░▓█
█▓░ (5) Update System		       (6) List Installed Packages           ░▓█
█▓░ (Q) EXIT                                                                 ░▓█
█▓░                                                                          ░▓█
█▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▓█
█▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓█
█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█
████████████████████████████████████████████████████████████████████████████████
"
  echo -e "${menu}"
  read -n 1 -p "Input Selection:" mainmenuinput
  echo ""
  if [ "$mainmenuinput" = "1" ]; then
      uninstallorphans
    elif [ "$mainmenuinput" = "2" ]; then
      pacmanclean
    elif [ "$mainmenuinput" = "3" ]; then
      deletecahe
    elif [ "$mainmenuinput" = "4" ]; then
      homdiruseage
    elif [ "$mainmenuinput" = "5" ]; then
      systemupdate      
    elif [ "$mainmenuinput" = "6" ]; then
      listinstalledsizes
    elif [ "$mainmenuinput" = "Q" ]; then
      exit
    elif [ "$mainmenuinput" = "q" ]; then
      exit

  fi
  mainmenu
}

mainmenu
