#!/usr/bin/python

import slugify

if __name__ == "__main__":
  if len(sys.argv) < 2:
    #print("Usage: slugify <text...>")
    sys.exit(1)

  text = " ".join(sys.argv[1:])
  #print(text)
  #slugify(text, max_length=32, word_boundary=True, stopwords=['a', 'and', 'the', 'or', 'if', 'is', 'but', 'yet'])

