#!/usr/bin/python
import sys
from slugify import slugify

if __name__ == "__main__":
  if len(sys.argv) < 2:
    #print("Usage: slugify <text...>")
    sys.exit(1)

  text = " ".join(sys.argv[1:])
  print(text)
  slugified = slugify(text, max_length=225, word_boundary=True, stopwords=["a", "of", "to", "for", "and", "the", "or", "if", "is", "but", "yet", "in", "it's", "its", "I"])
  print(slugified)

